import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const ticketApi = createApi({
  reducerPath: 'ticketApi',
  baseQuery: fetchBaseQuery({
    baseUrl: `${import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'}/api/tickettypes/`,
    credentials: 'include',
  }),
  refetchOnReconnect: true,
  refetchOnMountOrArgChange: true,

  tagTypes: ['ticketTypes', 'ticketType'],
  endpoints: (builder) => ({
    // 0. Get All Ticket Types
    getAllTicketTypes: builder.query({
      query: () => '',
      providesTags: ['ticketTypes'],
    }),

    // 1. Get All Ticket Types for an Event
    getTicketTypesByEventId: builder.query({
      query: (eventId) => `event/${eventId}`,
      providesTags: ['ticketTypes'],
    }),

    // 2. Check Ticket Type Availability
    checkTicketAvailability: builder.query({
      query: ({ ticketTypeId, quantity }) => `${ticketTypeId}/availability?quantity=${quantity}`,
    }),

    // 3. Count Total Ticket Types by Event
    countTicketTypesByEvent: builder.query({
      query: (eventId) => `event/${eventId}/count`,
    }),

    // 4. Get Ticket Type with Event Relation
    getTicketTypeWithEvent: builder.query({
      query: (ticketTypeId) => `${ticketTypeId}/with-event`,
    }),

    // 5. Get Total Remaining Tickets by Event
    getRemainingTicketsByEvent: builder.query({
      query: (eventId) => `event/${eventId}/remaining`,
    }),

    // 6. Get Available Ticket Types Only (Open & Un-sold-out)
    getAvailableTicketTypes: builder.query({
      query: (eventId) => `event/${eventId}/available`,
      providesTags: ['ticketTypes'],
    }),

    // 7. Check if Ticket Type is Sold Out
    checkIsSoldOut: builder.query({
      query: (ticketTypeId) => `${ticketTypeId}/sold-out`,
    }),

    // 8. Get Ticket Types by Price Range
    getTicketTypesByPriceRange: builder.query({
      query: ({ eventId, minPrice, maxPrice }) => `event/${eventId}/price-range?minPrice=${minPrice}&maxPrice=${maxPrice}`,
    }),

    // 9. Validate Ticket Type Belongs to Event
    validateTicketBelonging: builder.query({
      query: ({ ticketTypeId, eventId }) => `${ticketTypeId}/validate-belonging?eventId=${eventId}`,
    }),

    // 10. Get Ticket Type by ID
    getTicketTypeById: builder.query({
      query: (ticketTypeId) => `${ticketTypeId}`,
      providesTags: (_result, _error, ticketTypeId) => [{ type: 'ticketType', id: ticketTypeId }],
    }),

    // 11. Create a Single Ticket Type
    createTicketType: builder.mutation({
      query: (createTicketTypePayload) => ({
        url: '',
        method: 'POST',
        body: createTicketTypePayload,
      }),
      invalidatesTags: ['ticketTypes'],
    }),

    // 12. Bulk Create Ticket Types for an Event
    bulkCreateTicketTypes: builder.mutation({
      query: (bulkPayload) => ({
        url: 'bulk',
        method: 'POST',
        body: bulkPayload,
      }),
      invalidatesTags: ['ticketTypes'],
    }),

    // 13. Clone Ticket Types to a New Event
    cloneTicketTypes: builder.mutation({
      query: (clonePayload) => ({
        url: 'clone',
        method: 'POST',
        body: clonePayload,
      }),
      invalidatesTags: ['ticketTypes'],
    }),

    // 14. Update Ticket Type Details
    updateTicketType: builder.mutation({
      query: ({ ticketTypeId, ...body }) => ({
        url: `${ticketTypeId}`,
        method: 'PUT',
        body,
      }),
      invalidatesTags: (_result, _error, { ticketTypeId }) => ['ticketTypes', { type: 'ticketType', id: ticketTypeId }],
    }),

    // 15. Update Ticket Type Capacity
    updateTicketCapacity: builder.mutation({
      query: ({ ticketTypeId, quantity }) => ({
        url: `${ticketTypeId}/capacity`,
        method: 'PATCH',
        body: { quantity },
      }),
      invalidatesTags: (_result, _error, { ticketTypeId }) => ['ticketTypes', { type: 'ticketType', id: ticketTypeId }],
    }),

    // 16. Update Ticket Type Price
    updateTicketPrice: builder.mutation({
      query: ({ ticketTypeId, price }) => ({
        url: `${ticketTypeId}/price`,
        method: 'PATCH',
        body: { price },
      }),
      invalidatesTags: (_result, _error, { ticketTypeId }) => ['ticketTypes', { type: 'ticketType', id: ticketTypeId }],
    }),

    // 17. Delete Ticket Type
    deleteTicketType: builder.mutation({
      query: (ticketTypeId) => ({
        url: `${ticketTypeId}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['ticketTypes'],
    }),

    // 18. Delete All Ticket Types for an Event
    deleteAllTicketTypesForEvent: builder.mutation({
      query: (eventId) => ({
        url: `event/${eventId}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['ticketTypes'],
    }),

    // 19. Calculate Revenue Generated by a Specific Ticket Type
    getTicketTypeRevenue: builder.query({
      query: (ticketTypeId) => `${ticketTypeId}/revenue`,
    }),

    // 20. Get Total Cumulative Event Ticket Revenue
    getEventRevenue: builder.query({
      query: (eventId) => `event/${eventId}/revenue`,
    }),

    // 21. Get Comprehensive Event Inventory Summary Report
    getInventorySummary: builder.query({
      query: (eventId) => `event/${eventId}/inventory-summary`,
    }),

    // 22. Increment Tickets Sold Count
    incrementSold: builder.mutation({
      query: ({ ticketTypeId, count }) => ({
        url: `${ticketTypeId}/increment-sold`,
        method: 'PATCH',
        body: { count },
      }),
      invalidatesTags: (_result, _error, { ticketTypeId }) => ['ticketTypes', { type: 'ticketType', id: ticketTypeId }],
    }),

    // 23. Decrement Tickets Sold Count
    decrementSold: builder.mutation({
      query: ({ ticketTypeId, count }) => ({
        url: `${ticketTypeId}/decrement-sold`,
        method: 'PATCH',
        body: { count },
      }),
      invalidatesTags: (_result, _error, { ticketTypeId }) => ['ticketTypes', { type: 'ticketType', id: ticketTypeId }],
    }),

    // 24. Reset Tickets Sold Count Back to Zero
    resetSold: builder.mutation({
      query: (ticketTypeId) => ({
        url: `${ticketTypeId}/reset-sold`,
        method: 'PATCH',
      }),
      invalidatesTags: (_result, _error, ticketTypeId) => ['ticketTypes', { type: 'ticketType', id: ticketTypeId }],
    }),
  }),
});

export const {
  useGetAllTicketTypesQuery,
  useGetTicketTypesByEventIdQuery,
  useCheckTicketAvailabilityQuery,
  useCountTicketTypesByEventQuery,
  useGetTicketTypeWithEventQuery,
  useGetRemainingTicketsByEventQuery,
  useGetAvailableTicketTypesQuery,
  useCheckIsSoldOutQuery,
  useGetTicketTypesByPriceRangeQuery,
  useValidateTicketBelongingQuery,
  useGetTicketTypeByIdQuery,
  useCreateTicketTypeMutation,
  useBulkCreateTicketTypesMutation,
  useCloneTicketTypesMutation,
  useUpdateTicketTypeMutation,
  useUpdateTicketCapacityMutation,
  useUpdateTicketPriceMutation,
  useDeleteTicketTypeMutation,
  useDeleteAllTicketTypesForEventMutation,
  useGetTicketTypeRevenueQuery,
  useGetEventRevenueQuery,
  useGetInventorySummaryQuery,
  useIncrementSoldMutation,
  useDecrementSoldMutation,
  useResetSoldMutation,
} = ticketApi;